# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 894c418fd632647e43cf704a3cec4eef946afc371af314eab041132fcc31f195782db2c0ea180f5c9416dc272b5af5e9f5807f2d7ea6245adc5fce6b02ba4f21

test:
  secret_key_base: d9e9b3f0ba3697317596d9bf6c5f94e3a34181908a3341b1cde8943cf970077a8d7cfec83e0cc8fe4cc59d1f1aae6482c4139f698aa964eb4cc39aefbd58be2e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
